parameters:
    bd_guzzle_site_authenticator.site_config: []

services:
    bd_guzzle_site_authenticator.authenticator_plugin:
        class: BD\GuzzleSiteAuthenticator\Plugin\AuthenticatorPlugin
        arguments:
            - "@bd_guzzle_site_authenticator.site_config_builder"
            - "@bd_guzzle_site_authenticator.authenticator_factory"

    bd_guzzle_site_authenticator.authenticator_factory:
        class: BD\GuzzleSiteAuthenticator\Authenticator\Factory

    bd_guzzle_site_authenticator.site_config_builder:
        alias: bd_guzzle_site_authenticator.site_config_builder.array

    bd_guzzle_site_authenticator.site_config_builder.array:
        class: BD\GuzzleSiteAuthenticator\SiteConfig\ArraySiteConfigBuilder
        arguments:
            - "%bd_guzzle_site_authenticator.site_config%"

    bd_guzzle_site_authenticator.monde_diplomatique_uri_fix_subscriber:
        class: BD\GuzzleSiteAuthenticator\Guzzle\FixupMondeDiplomatiqueUriSubscriber
